// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7PKhLY2bJtZ8Bl_SwY8sN04egYnu0U8',
    appId: '1:898061521037:web:124c2ee706ec695694d2c4',
    messagingSenderId: '898061521037',
    projectId: 'onlineshoppingapp-237c7',
    authDomain: 'onlineshoppingapp-237c7.firebaseapp.com',
    storageBucket: 'onlineshoppingapp-237c7.firebasestorage.app',
    measurementId: 'G-01CMC0ZGHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaD9nwKlQ4lxHHoW0ajNnukuuCjvgCo7U',
    appId: '1:898061521037:android:095edbf5a32fd9fe94d2c4',
    messagingSenderId: '898061521037',
    projectId: 'onlineshoppingapp-237c7',
    storageBucket: 'onlineshoppingapp-237c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxDRZ2NH7Neff_52VzKsLBpxg5HXzuRo',
    appId: '1:898061521037:ios:d5fb43de4d191bb794d2c4',
    messagingSenderId: '898061521037',
    projectId: 'onlineshoppingapp-237c7',
    storageBucket: 'onlineshoppingapp-237c7.firebasestorage.app',
    iosClientId:
        '898061521037-t2tndp64im4vt9mua6gdr1q2boab9apd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxDRZ2NH7Neff_52VzKsLBpxg5HXzuRo',
    appId: '1:898061521037:ios:d5fb43de4d191bb794d2c4',
    messagingSenderId: '898061521037',
    projectId: 'onlineshoppingapp-237c7',
    storageBucket: 'onlineshoppingapp-237c7.firebasestorage.app',
    iosClientId:
        '898061521037-t2tndp64im4vt9mua6gdr1q2boab9apd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN7PKhLY2bJtZ8Bl_SwY8sN04egYnu0U8',
    appId: '1:898061521037:web:9a4c249c945c54b494d2c4',
    messagingSenderId: '898061521037',
    projectId: 'onlineshoppingapp-237c7',
    authDomain: 'onlineshoppingapp-237c7.firebaseapp.com',
    storageBucket: 'onlineshoppingapp-237c7.firebasestorage.app',
    measurementId: 'G-RG37XNG5MJ',
  );
}
